# Generated by Django 3.2.4 on 2021-06-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lasttname', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Studentpics')),
                ('age', models.IntegerField()),
            ],
        ),
    ]
